version: '3'
services:
  app:
    build:
      args:
        user: app
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    image: app
    restart: unless-stopped
    working_dir: /home/app/
    volumes:
      - ./:/home/app/
    environment:
      - DEBUG=test123
    ports:
      - 3000:3000
    networks:
      - myNetwork

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - myNetwork

  # phpmyadmin
  phpmyadmin:
    image: 'phpmyadmin'
    container_name: phpmyadmin
    environment:
        PMA_HOST: mysql
        PMA_PASSWORD: laravel
        PMA_ARBITRARY: 1
    restart: always
    ports:
        - 8080:80
    networks:
        - myNetwork
        
#Docker Networks
networks:
  myNetwork:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local